common:

  homepage: "https://exporter.nih.gov"

  output:

    # relative to the directory where the script is run
    downloads directory: downloads

    # relative to the `downloads directory`
    unzipped files directory: unzipped

projects:

  # to be used when saving
  name: projects

  # the URL (relative to the above "homepage") where to find projects data
  relative path: "ExPORTER_Catalog.aspx?sid=1&index=0"

  # the position of the table of interest when considering all the tables in the URL
  table number: &nih_projects_table_number 12

  # the name of the (feather) file in/from which the data will be saved/loaded
  feather file: projects.feather

  # (Python) regular expressions for (linked) files to be ignored
  filename patterns to be ignored:
    - ^javascript.*
    - .*_DUNS_.*\.zip$
    - .*_PRJFUNDING_.*\.zip$

  # columns that unequivocally identify elements here (they need not be unique)
  key columns: [CORE_PROJECT_NUM]

  # data types specification (you probably don't want to mess with this); if blank, it is inferred
  data types:

    # these were obtained by *adapting* those returned  by `util.dataframe_types_to_yaml`
    ACTIVITY: object
    ADMINISTERING_IC: object
    APPLICATION_ID: int64
    APPLICATION_TYPE: float64
    ARRA_FUNDED: object
    AWARD_NOTICE_DATE: object
    BUDGET_END: object
    BUDGET_START: object
    CFDA_CODE: object
    CORE_PROJECT_NUM: object
    DIRECT_COST_AMT: float64
    ED_INST_TYPE: object
    FOA_NUMBER: object
    FULL_PROJECT_NUM: object
    FUNDING_ICs: object
    FUNDING_MECHANISM: object
    FY: int64
    IC_NAME: object
    INDIRECT_COST_AMT: float64
    NIH_SPENDING_CATS: object
    ORG_CITY: object
    ORG_COUNTRY: object
    ORG_DEPT: object
    ORG_DISTRICT: float64
    ORG_DUNS: object
    ORG_FIPS: object
    ORG_IPF_CODE: float64
    ORG_NAME: object
    ORG_STATE: object
    ORG_ZIPCODE: object
    PHR: object
    PI_IDS: object
    PI_NAMEs: object
    PROGRAM_OFFICER_NAME: object
    PROJECT_END: object
    PROJECT_START: object
    PROJECT_TERMS: object
    PROJECT_TITLE: object
    SERIAL_NUMBER: object
    STUDY_SECTION: object
    STUDY_SECTION_NAME: object
    SUBPROJECT_ID: float64
    SUFFIX: object
    SUPPORT_YEAR: object
    TOTAL_COST: float64
    TOTAL_COST_SUB_PROJECT: float64

publications:

  name: publications

  relative path: "ExPORTER_Catalog.aspx?sid=0&index=2"

  table number: *nih_projects_table_number

  feather file: publications.feather

  filename patterns to be ignored:
    - ^javascript.*
    - .*_AFFLNK_.*\.zip$

  key columns: [PMID]

  data types:

link tables:

  name: link

  relative path: "ExPORTER_Catalog.aspx?sid=2&index=5"

  table number: *nih_projects_table_number

  feather file: link.feather

  filename patterns to be ignored: []

  key columns: [PMID, PROJECT_NUMBER]

  data types:

patents:

  name: patents

  relative path: "ExPORTER_Catalog.aspx?sid=2&index=3"

  table number: *nih_projects_table_number

  feather file: patents.feather

  filename patterns to be ignored: []

  key columns: [PATENT_ID, PROJECT_ID]

  data types:
